/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/baetyl/baetyl-controller/kube/apis/baetyl/v1alpha1"
	scheme "github.com/baetyl/baetyl-controller/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppliesGetter has a method to return a ApplyInterface.
// A group's client should implement this interface.
type AppliesGetter interface {
	Applies(namespace string) ApplyInterface
}

// ApplyInterface has methods to work with Apply resources.
type ApplyInterface interface {
	Create(ctx context.Context, apply *v1alpha1.Apply, opts v1.CreateOptions) (*v1alpha1.Apply, error)
	Update(ctx context.Context, apply *v1alpha1.Apply, opts v1.UpdateOptions) (*v1alpha1.Apply, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Apply, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ApplyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Apply, err error)
	ApplyExpansion
}

// applies implements ApplyInterface
type applies struct {
	client rest.Interface
	ns     string
}

// newApplies returns a Applies
func newApplies(c *BaetylV1alpha1Client, namespace string) *applies {
	return &applies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the apply, and returns the corresponding apply object, and an error if there is any.
func (c *applies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Applies that match those selectors.
func (c *applies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApplyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ApplyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested applies.
func (c *applies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a apply and creates it.  Returns the server's representation of the apply, and an error, if there is any.
func (c *applies) Create(ctx context.Context, apply *v1alpha1.Apply, opts v1.CreateOptions) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apply).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a apply and updates it. Returns the server's representation of the apply, and an error, if there is any.
func (c *applies) Update(ctx context.Context, apply *v1alpha1.Apply, opts v1.UpdateOptions) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("applies").
		Name(apply.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apply).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the apply and deletes it. Returns an error if one occurs.
func (c *applies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *applies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched apply.
func (c *applies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Apply, err error) {
	result = &v1alpha1.Apply{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("applies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
